### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [BrunoJuchli/StaticProxy.Fody#10]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by BrunoJuchli** [comment]
Note to self: Mono Cecil changes: http://cecil.pe/post/149243207656/mono-cecil-010-beta-1
Notably disposal of modules!

**Comment by BrunoJuchli** [comment]
@SimonCropp 
Thank a lot for maintaining Fody and for letting me know about the update.
I'm done updating the addin.

Time to get my related packages .net standard ready...
