### ISSUE TITLE
Proxy class from external library

### ISSUE THREAD

**Issue by innuendonh** [BrunoJuchli/StaticProxy.Fody#11]
Hello,
would it be possible to proxy all property accesses performed on a specific variable (or better, class attribute)?

For Example, I would like to replace every read to `myvariable.myproperty` with, e.g., `mygetter(myvariable.myproperty)`, where myvariable is a type defined in mscore, e.g., BindingSource.

(I'm trying to workaround some issues in legacy code)

Thank you!

**Comment by BrunoJuchli** [comment]
proxying external library types is not possible as this tool requires to be part of the build chain of the library it modifies to have proxies.
