### ISSUE TITLE
Running Example

### ISSUE THREAD

**Issue by knight1219** [BrunoJuchli/StaticProxy.Fody#8]
Is there a running example of how to get started with this weaver anywhere? Not just snips here and there but a complete solution with how to setup the different IoL containers and whatnot?

**Comment by BrunoJuchli** [comment]
https://github.com/BrunoJuchli/StaticProxy.ManualIntegrationTest

Has a very simple demo application using both Unity and Ninject.

I'll see if a can provide something better next week. What do you have in mind? What should the sample application cover?

**Comment by knight1219** [comment]
Fantastic! I have it running.

Now, I add a new Class Library (Xamarin PCL), add the StaticProxy.Fody and StaticProxy.Interceptors NUgets and try to move the Proxied and FakeInterceptor classes into that run it and I get the following build error:

Fody: There needs to be exactly one type with FullName 'StaticProxyAttribute', but 0 were found.	ManualNugetIntegrationTest			

I thought I read that this is Xamarin PCL compatible? Is there something I'm doing wrong?

**Comment by BrunoJuchli** [comment]
Can you upload your code so i can have a look?

**Comment by knight1219** [comment]
[PCLStaticProxyTest.zip](https://github.com/BrunoJuchli/StaticProxy.Fody/files/230536/PCLStaticProxyTest.zip)

Here is the test solution I have. What I'm wanting to do is I have my project setup in such a way that my PCL libraries are my controllers and I have both Xamarin and Desktop projects that use them. I want to add logging and tracing to the PCL libraries so my UI code doesn't need to know about it.

**Comment by BrunoJuchli** [comment]
It's as i thought. I've improved the error message (but i'm going to hold off on publishing a new version until i've resolved the build issues on appveyor where it can't build the PCL packages properly - i had to build the last packages on my own computer).

So what you need to do is de-uncomment the code in ManuelNugetIntegrationTests Proxied.cs or uninstall StaticProxy.Fody from ManuelNugetIntegrationTests.

**Comment by knight1219** [comment]
That did it! Thanks!
