### ISSUE TITLE
Error with Multiple Constructors - Static Constructor

### ISSUE THREAD

**Issue by ES-2000** [BrunoJuchli/StaticProxy.Fody#9]
If you have static fields in your class, which contains the static proxy attribute, you got an error for having multiple constructors while weaving (ctor, cctor).

your source code do not show a different behaviour on handling those kinds of constructors. did you forget this case or is there something, that do not allow you to seperate the workflow.

**Comment by BrunoJuchli** [comment]
I'll have a look at it in the next few days. I'm not a 100% sure that I correctly understand what you are saying though. Could you provide exemplar code, please?

**Comment by ES-2000** [comment]
sure! here is an example:

```csharp
/// <summary>
/// there is no constructor defined
/// default constructor (ctor) will be created
/// </summary>
[StaticProxy]
public class ClassWithStaticConstructor
{
    /// <summary>
    /// creates a static constructor (cctor)
    /// </summary>
    private static HashSet<int> hashSet = new HashSet<int>()
    {
        1,
        2,
        3
    };
}
```

this causes the following error: Fody: Static Proxy issue with type 'ClassWithStaticConstructor'. Static Proxy does not support proxying classes with multiple constructors.

your code contains the following check:
```csharp
private static bool HasMultipleConstructors(TypeDefinition typeDefinition)
{
    return typeDefinition.GetConstructors().Count() > 1;
}
```

GetConstructors() returns two constructors. the default one (ctor) and the static one (cctor).
my question is: why isn't there a different handling? i would say static constructor shouldn't be handled like other constructors. so is there any reason or is this a bug?

**Comment by BrunoJuchli** [comment]
It's a bug. I'll have a look into fixing it. Probably should be able to just ignore all static constructors. They can't be called from code anyway...

**Comment by BrunoJuchli** [comment]
Sorry, the close was a bit preliminary... In a few minutes I'll upload StaticProxy.Fody 0.3.0.102 to nuget.org which will include the fix.
